# Generated by Django 3.1.1 on 2020-09-08 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification_app', '0001_initial'),
        ('tweet_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='tracked_tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweet_app.tweet'),
        ),
    ]
