# Generated by Django 3.1.1 on 2020-09-03 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_body', models.TextField(max_length=255)),
                ('time_submitted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
