# Generated by Django 3.1.1 on 2020-09-04 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterusermodel',
            name='following',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
