# Generated by Django 3.1.1 on 2020-09-07 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser_app', '0002_twitterusermodel_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterusermodel',
            name='following',
        ),
        migrations.AddField(
            model_name='twitterusermodel',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
